[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "Unlicense", "Zlib", "0BSD", "ISC", "LGPL-3.0-or-later", "BSD-3-Clause"]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
